Repository akka/alpakka, pull requests merged in 2018-12, with the labels that each got.

#1361 Akka 2.5.19 upgrade
  avroparquet/src/test/java/docs/javadsl/AvroParquetSinkTest.java
  jms/src/test/scala/akka/stream/alpakka/jms/JmsProducerRetrySpec.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  project/Dependencies.scala
Labels: alpakka-itself, p:mqtt-streaming

#1363 Solr: partition changes the order.
  solr/src/main/scala/akka/stream/alpakka/solr/SolrFlowStage.scala
Labels: p:solr

#1368 Show dependencies in all docs
  docs/src/main/paradox/amqp.md
  docs/src/main/paradox/avroparquet.md
  docs/src/main/paradox/awslambda.md
  docs/src/main/paradox/azure-storage-queue.md
  docs/src/main/paradox/cassandra.md
  docs/src/main/paradox/couchbase.md
  docs/src/main/paradox/data-transformations/csv.md
  docs/src/main/paradox/data-transformations/json.md
  docs/src/main/paradox/data-transformations/recordio.md
  docs/src/main/paradox/data-transformations/text.md
  docs/src/main/paradox/data-transformations/xml.md
  docs/src/main/paradox/dynamodb.md
  docs/src/main/paradox/elasticsearch.md
  docs/src/main/paradox/file.md
  docs/src/main/paradox/ftp.md
  docs/src/main/paradox/geode.md
  docs/src/main/paradox/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/google-cloud-pub-sub.md
  docs/src/main/paradox/google-fcm.md
  docs/src/main/paradox/hbase.md
  docs/src/main/paradox/hdfs.md
  docs/src/main/paradox/ironmq.md
  docs/src/main/paradox/kinesis.md
  docs/src/main/paradox/kudu.md
  docs/src/main/paradox/mongodb.md
  docs/src/main/paradox/mqtt-streaming.md
  docs/src/main/paradox/mqtt.md
  docs/src/main/paradox/orientdb.md
  docs/src/main/paradox/reference.md
  docs/src/main/paradox/s3.md
  docs/src/main/paradox/slick.md
  docs/src/main/paradox/sns.md
  docs/src/main/paradox/solr.md
  docs/src/main/paradox/spring-web.md
  docs/src/main/paradox/sqs.md
  docs/src/main/paradox/sse.md
  docs/src/main/paradox/udp.md
  docs/src/main/paradox/unix-domain-socket.md
  project/plugins.sbt
Labels: alpakka-itself

#1336 AWS SQS: Improve SqsAckResult and SqsPublishResult consistency
  docs/src/main/paradox/sqs.md
  sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchException.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsAckFlowStage.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchChangeMessageVisibilityFlowStage.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchDeleteFlowStage.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchFlowStage.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchStageLogic.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsFlowStage.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsSourceStage.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala
  sqs/src/test/java/docs/javadsl/SqsAckTest.java
  sqs/src/test/java/docs/javadsl/SqsPublishTest.java
  sqs/src/test/java/docs/javadsl/SqsSourceTest.java
  sqs/src/test/scala/akka/stream/alpakka/sqs/SqsModelSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Labels: p:aws-sqs

#1373 Moving ParseEventMarker to akka.stream.alpakka.xml package
  xml/src/main/java/akka/stream/alpakka/xml/ParseEventMarker.java
  xml/src/main/scala/akka/stream/alpakka/xml/model.scala
Labels: api-change, p:xml

#1366 ES: Making the scroll value configurable
  docs/src/main/paradox/elasticsearch.md
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceSettings.scala
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
  elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
Labels: p:elasticsearch

#1370 Show project info
  docs/src/main/paradox/amqp.md
  docs/src/main/paradox/avroparquet.md
  docs/src/main/paradox/awslambda.md
  docs/src/main/paradox/azure-storage-queue.md
  docs/src/main/paradox/cassandra.md
  docs/src/main/paradox/couchbase.md
  docs/src/main/paradox/data-transformations/csv.md
  docs/src/main/paradox/data-transformations/json.md
  docs/src/main/paradox/data-transformations/recordio.md
  docs/src/main/paradox/data-transformations/text.md
  docs/src/main/paradox/data-transformations/xml.md
  docs/src/main/paradox/dynamodb.md
  docs/src/main/paradox/elasticsearch.md
  docs/src/main/paradox/file.md
  docs/src/main/paradox/ftp.md
  docs/src/main/paradox/geode.md
  docs/src/main/paradox/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/google-cloud-pub-sub.md
  docs/src/main/paradox/google-fcm.md
  docs/src/main/paradox/hbase.md
  docs/src/main/paradox/hdfs.md
  docs/src/main/paradox/ironmq.md
  docs/src/main/paradox/kinesis.md
  docs/src/main/paradox/kudu.md
  docs/src/main/paradox/mongodb.md
  docs/src/main/paradox/mqtt-streaming.md
  docs/src/main/paradox/mqtt.md
  docs/src/main/paradox/orientdb.md
  docs/src/main/paradox/s3.md
  docs/src/main/paradox/slick.md
  docs/src/main/paradox/sns.md
  docs/src/main/paradox/solr.md
  docs/src/main/paradox/spring-web.md
  docs/src/main/paradox/sqs.md
  docs/src/main/paradox/sse.md
  docs/src/main/paradox/udp.md
  docs/src/main/paradox/unix-domain-socket.md
  project/Common.scala
  project/plugins.sbt
  project/project-info.conf
Labels: alpakka-itself

#1374 :arrow_up: Geode 1.8.0
  build.sbt
  docker-compose.yml
  project/Dependencies.scala
Labels: p:geode

#1369 Filter generated protobuf classes from scaladoc
  build.sbt
  project/Common.scala
Labels: alpakka-itself

#1386 Ignore mongodb classes from scaladoc
  project/Common.scala
Labels: alpakka-itself

#1391 Depend on patched version of sbt-dependency-graph
  project/plugins.sbt
Labels: alpakka-itself

#1392 Support Whitesource groups
  project/Common.scala
  project/Whitesource.scala
Labels: alpakka-itself

#1389 Use Community-driven instead of Incubating
  project/plugins.sbt
  project/project-info.conf
Labels: alpakka-itself

#1393 Use adopt OpenJDK 8
  .travis.yml
Labels: alpakka-itself

#1387 MQTT streaming: Connection hardening
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: p:mqtt-streaming

#1394 MQTT streaming: More connection failure hardening
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: p:mqtt-streaming

#1390 Release Train template
  RELEASING.md
  docs/release-train-issue-template.md
Labels: alpakka-itself

#1332 AWS S3 - allow to get object metadata without size limit
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
Labels: p:aws-s3

#1396 MQTT: Fix API link
  docs/src/main/paradox/mqtt.md
Labels: p:mqtt

#1397 Licensing: Explicitly depend on jaxb-impl 2.2.3-1 in Hbase
  project/Dependencies.scala
Labels: p:hbase

#1376 Use to Jackson 2.9.8, Spray Json 1.3.5
  build.sbt
  elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
  project/Dependencies.scala
Labels: alpakka-itself, dependency-change, p:elasticsearch

#1372 FTP: Upgrade dependencies
  ftp/src/test/java/akka/stream/alpakka/ftp/SftpSupportImpl.java
  project/Dependencies.scala
Labels: p:ftp

#1398 CSV: Accept CR, CR, LF line-endings
  csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvParsing.java
  csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
  csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
Labels: p:csv
