Repository akka/alpakka, pull requests merged in 2019-03, with the labels that each got.

#1544 Update to Alpakka Kafka 1.0
  project/Dependencies.scala
Labels: alpakka-itself

#1541 CSV: Adapt to Scala 2.13
  build.sbt
  csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvFormatting.java
  csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
Labels: p:csv

#1539 Add M3 release notes
  docs/src/main/paradox/release-notes/1.0-M3.md
  docs/src/main/paradox/release-notes/index.md
Labels: alpakka-itself

#1551 Split publish job across Scala versions
  .travis.yml
  docs/src/main/paradox/release-notes/1.0-M3.md
Labels: alpakka-itself

#1297 Unix Domain Socket - Bump jnr-enxio and remove local fix
  build.sbt
  project/Dependencies.scala
  unix-domain-socket/src/main/java/jnr/enxio/channels/KQSelector.java
  unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/impl/UnixDomainSocketImpl.scala
  unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
Labels: p:unix-domain-socket

#1545 Add maxOpenRequests param in DynamoConfig
  dynamodb/src/main/resources/reference.conf
  dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/DynamoSettings.scala
  dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
  dynamodb/src/test/java/docs/javadsl/ExampleTest.java
  dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/DynamoSettingsSpec.scala
Labels: enhancement, p:dynamodb

#1456 AWS Lambda: use AWS SDK v2 instead of AWS SDK v1
  awslambda/src/main/scala/akka/stream/alpakka/awslambda/impl/AwsLambdaFlowStage.scala
  awslambda/src/main/scala/akka/stream/alpakka/awslambda/javadsl/AwsLambdaFlow.scala
  awslambda/src/main/scala/akka/stream/alpakka/awslambda/scaladsl/AwsLambdaFlow.scala
  awslambda/src/test/java/docs/javadsl/AwsLambdaFlowTest.java
  awslambda/src/test/java/docs/javadsl/Examples.java
  awslambda/src/test/scala/docs/scaladsl/AwsLambdaFlowSpec.scala
  awslambda/src/test/scala/docs/scaladsl/Examples.scala
  docs/src/main/paradox/awslambda.md
  project/Dependencies.scala
Labels: enhancement, p:aws-lambda

#1560 S3: add deleteByPrefix method
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
  s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Labels: enhancement, p:aws-s3

#1555 Update availability section
  docs/release-train-issue-template.md
Labels: alpakka-itself

#1562 Upgrade to the latest sbt-scalafmt
  .scalafmt.conf
  build.sbt
  project/plugins.sbt
Labels: alpakka-itself

#1557 Lazy source and flow
  unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/impl/UnixDomainSocketImpl.scala
  unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
Labels: p:unix-domain-socket

#1556 Change mat value to Future in multiPartUpload/Copy
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
  s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
  s3/src/test/java/docs/javadsl/S3Test.java
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
  s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
Labels: api-change, enhancement, p:aws-s3

#1570 AWS S3: Remove left-overs from #1556
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Labels: p:aws-s3

#1561 Mqtt streaming: assertAllStageStopped
  docs/src/main/paradox/mqtt-streaming.md
  mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
  mqtt-streaming/src/test/resources/application.conf
  mqtt-streaming/src/test/resources/logback-test.xml
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: p:mqtt-streaming

#1574 Add example .htaccess file
  docs/src/main/paradox/.htaccess
Labels: alpakka-itself

#1567 Make generated docs xhtml compliant
  docs/src/main/paradox/overview.md
  docs/src/main/paradox/release-notes/1.0-M1.md
  docs/src/main/paradox/release-notes/1.0-M2.md
  docs/src/main/paradox/release-notes/1.0-M3.md
  s3/src/main/scala/akka/stream/alpakka/s3/model.scala
  xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlParsing.scala
Labels: alpakka-itself

#1568 Default to https in doc links
  build.sbt
Labels: alpakka-itself

#1573 Cassandra: API may change
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraFlow.scala
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSink.scala
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSource.scala
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSink.scala
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSource.scala
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/settings.scala
  docs/src/main/paradox/cassandra.md
Labels: p:cassandra

#1564 Update akka-grpc to 0.6
  build.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: p:google-cloud-pub-sub-grpc

#1569 Fix Alpakka theme, add canonical URL and description
  build.sbt
  docs/src/main/paradox/_template/logo.st
  docs/src/main/paradox/_template/projectSpecificFooter.st
  docs/src/main/paradox/release-notes/1.0-M2.md
  docs/src/main/paradox/release-notes/1.0-M3.md
  project/Common.scala
  project/plugins.sbt
Labels: alpakka-itself

#1583 Hack to allow CDATA in footer
  docs/src/main/paradox/_template/projectSpecificFooter.st
Labels: alpakka-itself

#1585 Use setup stage and attrbutes for external resources
  docs/src/main/paradox/reference.md
  reference/src/main/resources/application.conf
  reference/src/main/scala/akka/stream/alpakka/reference/Resource.scala
  reference/src/main/scala/akka/stream/alpakka/reference/attributes.scala
  reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceWithResourceFlow.scala
  reference/src/main/scala/akka/stream/alpakka/reference/impl/SetupStage.scala
  reference/src/main/scala/akka/stream/alpakka/reference/javadsl/Reference.scala
  reference/src/main/scala/akka/stream/alpakka/reference/javadsl/ReferenceWithResource.scala
  reference/src/main/scala/akka/stream/alpakka/reference/scaladsl/Reference.scala
  reference/src/main/scala/akka/stream/alpakka/reference/scaladsl/ReferenceWithResource.scala
  reference/src/test/java/docs/javadsl/ReferenceTest.java
  reference/src/test/java/docs/javadsl/ReferenceWithResourceTest.java
  reference/src/test/scala/docs/scaladsl/ReferenceSpec.scala
  reference/src/test/scala/docs/scaladsl/ReferenceWithResourceSpec.scala
Labels: p:reference

#1592 Termination signal handling
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
Labels: p:mqtt-streaming

#1586 Release notes 1.0-RC1
  docs/src/main/paradox/release-notes/1.0-RC1.md
  docs/src/main/paradox/release-notes/index.md
Labels: alpakka-itself

#1593 Fix typo: parallism -> parallelism
  slick/src/test/java/docs/javadsl/DocSnippetFlowWithPassThrough.java
  slick/src/test/java/docs/javadsl/DocSnippetSink.java
  slick/src/test/scala/docs/scaladsl/DocSnippets.scala
Labels: p:slick

#1587 Run MiMa on Travis
  .travis.yml
  build.sbt
Labels: alpakka-itself

#1606 SQS: add MessageFactory
  sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala
Labels: p:aws-sqs

#1605 Fix SqsSource back-pressure and memory leak
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
Labels: p:aws-sqs

#1603 MQTT Streaming: Fix keepalive
  mqtt-streaming/src/main/mima-filters/1.0-RC1.backwards.excludes
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
Labels: p:mqtt-streaming

#1595 mqtt-streaming: Various fixes
  mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/MqttPerf.scala
  mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttPerf.scala
  mqtt-streaming/src/main/mima-filters/1.0-RC1.backwards.excludes
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/javadsl/Mqtt.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
  mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: p:mqtt-streaming

#1607 Docs: fix more dead links
  docs/src/main/paradox/amqp.md
  docs/src/main/paradox/cassandra.md
  docs/src/main/paradox/couchbase.md
  docs/src/main/paradox/ironmq.md
  docs/src/main/paradox/jms/producer.md
  docs/src/main/paradox/kinesis.md
  docs/src/main/paradox/orientdb.md
  docs/src/main/paradox/reference.md
Labels: alpakka-itself

#1597 Minor release template improvement
  docs/release-train-issue-template.md
Labels: alpakka-itself

#1614 mqtt-streaming: Server shouldn't stash PUBLISH for uninterested clients
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
Labels: p:mqtt-streaming

#1612 Fix more links to API docs
  docs/src/main/paradox/examples/mqtt-samples.md
  docs/src/main/paradox/ftp.md
  docs/src/main/paradox/google-fcm.md
  docs/src/main/paradox/release-notes/1.0-M2.md
Labels: alpakka-itself

#1613 Add organization homepage setting
  project/Common.scala
Labels: alpakka-itself

#1596 Scalatest 3.0.7 and plugin updgrades
  project/Dependencies.scala
  project/plugins.sbt
Labels: alpakka-itself
