Repository akka/alpakka, pull requests merged in 2019-06, with the labels that each got.

#1739 Update formatting fix instructions
  .travis.yml
Labels: alpakka-itself

#1738 AWS S3: Fix plus char usage in s3 key
  s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequest.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequestSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SignerSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Labels: p:aws-s3

#1741 Google Cloud Pub/Sub gRPC: Update to the latest akka-grpc
  project/plugins.sbt
Labels: p:google-cloud-pub-sub-grpc

#1745 Couchbase: Propagate replicateTo setting when using CouchbaseSession.insert #1744
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionImpl.scala
Labels: p:couchbase

#1748 S3: Empty exception issue #1589
  s3/src/main/scala/akka/stream/alpakka/s3/S3Exception.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Labels: p:aws-s3

#1751 Explain MiMa use for contributors
  .travis.yml
  CONTRIBUTING.md
Labels: documentation

#1754 Release helper tools and auto labeling
  .github/autolabeler.yml
  RELEASING.md
  build.sbt
  docs/release-train-issue-template.md
  scripts/create-release-issue.sh
Labels: alpakka-itself

#1753 Move "Kafka to Elasticsearch" example
  doc-examples/src/main/java/elastic/KafkaToElasticInJava.java
  doc-examples/src/main/scala/elastic/KafkaToElastic.scala
  docs/src/main/paradox/examples/elasticsearch-samples.md
  project/Dependencies.scala
Labels: documentation

#1757 AWS SDK 2.5.65
  project/Dependencies.scala
Labels: dependency-change, p:aws-lambda, p:aws-sns, p:aws-sqs

#1758 Mockito 2.28.2
  project/Dependencies.scala
Labels: dependency-change, p:aws-lambda, p:aws-sns, p:aws-sqs, p:google-cloud-pub-sub, p:google-fcm, p:jms, p:kinesis

#1756 AWS SNS and SQS: Apache HTTP client is not used
  project/Dependencies.scala
Labels: dependency-change, p:aws-lambda, p:aws-sns, p:aws-sqs, p:elasticsearch

#1759 Use projectInfoVersion for paths of generated docs
  build.sbt
Labels: alpakka-itself

#1755 Versions for Scala 2.13.0
  .travis.yml
  build.sbt
  project/Common.scala
  project/Dependencies.scala
  sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
Labels: dependency-change, p:google-cloud-pub-sub, p:google-fcm, p:hdfs, p:slick, p:sse

#1747 Ack MqttMessage in Sink Flow
  docs/src/main/paradox/mqtt.md
  mqtt/src/main/mima-filters/1.0.x.backwards.excludes
  mqtt/src/main/scala/akka/stream/alpakka/mqtt/impl/MqttFlowStage.scala
  mqtt/src/main/scala/akka/stream/alpakka/mqtt/impl/MqttFlowStageWithAck.scala
  mqtt/src/main/scala/akka/stream/alpakka/mqtt/javadsl/MqttFlow.scala
  mqtt/src/main/scala/akka/stream/alpakka/mqtt/javadsl/MqttMessageWithAck.scala
  mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttFlow.scala
  mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttMessageWithAck.scala
  mqtt/src/test/java/docs/javadsl/MqttFlowTest.java
  mqtt/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
  mqtt/src/test/travis/acl
Labels: documentation, p:mqtt

#1766 Elasticsearch: use proper FlowWithContext
  elasticsearch/src/main/mima-filters/1.0.2.backwards.excludes
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
Labels: p:elasticsearch

#1765 Use Akka's setup operator
  amqp/src/test/java/docs/javadsl/AmqpDocsTest.java
  cassandra/src/test/java/docs/javadsl/CassandraSourceTest.java
  couchbase/src/main/mima-filters/1.0.x.backwards.excludes
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/SetupStage.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseFlow.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSource.scala
  dynamodb/src/main/mima-filters/1.0.x.backwards.excludes
  dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/SetupStage.scala
  dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoDb.scala
  elasticsearch/src/test/java/docs/javadsl/ElasticsearchTest.java
  google-cloud-pub-sub-grpc/src/main/mima-filters/1.0.x.backwards.excludes
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/impl/SetupStage.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GooglePubSub.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GooglePubSub.scala
  google-fcm/src/main/mima-filters/1.0.x.backwards.excludes
  google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmFlows.scala
  google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/SetupStage.scala
  google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmSenderSpec.scala
  google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApiSpec.scala
  hdfs/src/test/java/docs/javadsl/HdfsWriterTest.java
  jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java
  jms/src/test/java/docs/javadsl/JmsBufferedAckConnectorsTest.java
  jms/src/test/java/docs/javadsl/JmsConnectorsTest.java
  jms/src/test/java/docs/javadsl/JmsTxConnectorsTest.java
  kudu/src/main/mima-filters/1.0.x.backwards.excludes
  kudu/src/main/scala/akka/stream/alpakka/kudu/impl/SetupStage.scala
  kudu/src/main/scala/akka/stream/alpakka/kudu/scaladsl/KuduTable.scala
  mongodb/src/test/java/docs/javadsl/MongoSinkTest.java
  mongodb/src/test/java/docs/javadsl/MongoSourceTest.java
  mqtt/src/test/java/docs/javadsl/MqttSourceTest.java
  orientdb/src/test/java/docs/javadsl/OrientDbTest.java
  reference/src/main/scala/akka/stream/alpakka/reference/impl/SetupStage.scala
  reference/src/main/scala/akka/stream/alpakka/reference/scaladsl/Reference.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/SetupStage.scala
  slick/src/test/java/docs/javadsl/DocSnippetFlowWithPassThrough.java
  slick/src/test/java/docs/javadsl/SlickTest.java
  text/src/test/java/docs/javadsl/CharsetCodingFlowsDoc.java
Labels: p:amqp, p:aws-s3, p:cassandra, p:couchbase, p:elasticsearch, p:google-cloud-pub-sub-grpc, p:google-fcm, p:hbase, p:hdfs, p:jms, p:kudu, p:mongodb, p:mqtt, p:orientdb, p:reference

#1340 Google cloud storage support
  .travis.yml
  build.sbt
  docs/src/main/paradox/google-cloud-storage.md
  docs/src/main/paradox/index.md
  google-cloud-storage/src/main/resources/reference.conf
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/Bucket.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/FailedUpload.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCStorageAttributes.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCStorageExt.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCStorageSettings.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/ObjectNotFoundException.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageSettings.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/BucketInfo.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/BucketListResult.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/Chunker.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/Formats.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GoogleSession.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GoogleTokenApi.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/MultiPartUpload.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/RewriteResponse.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/SetupStage.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/TokenApiSettings.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/UploadPartResponse.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/javadsl/GCStorage.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/scaladsl/GCStorage.scala
  google-cloud-storage/src/test/java/docs/javadsl/GCStorageTest.java
  google-cloud-storage/src/test/resources/application.conf
  google-cloud-storage/src/test/resources/logback-test.xml
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/GCStorageExtSpec.scala
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/GCStorageSettingsSpec.scala
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/WithMaterializerGlobal.scala
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/impl/ChunkerSpec.scala
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/impl/GoogleTokenApiSpec.scala
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/scaladsl/GCStorageWiremockBase.scala
  google-cloud-storage/src/test/scala/docs/scaladsl/GCStorageSinkSpec.scala
  google-cloud-storage/src/test/scala/docs/scaladsl/GCStorageSourceSpec.scala
  project/Dependencies.scala
  project/project-info.conf
Labels: documentation, p:google-cloud-storage, p:new

#1743 AWS SQS source: reduce consumption on empty receives
  sqs/src/main/scala/akka/stream/alpakka/sqs/impl/BalancingMapAsync.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala
Labels: p:aws-sqs

#1752 Add `withProperties` to all jms message types
  jms/src/main/scala/akka/stream/alpakka/jms/JmsMessages.scala
Labels: p:jms

#1776 Nitpick: lower-case connector
  docs/src/main/paradox/awslambda.md
  docs/src/main/paradox/other-docs/webinars-presentations-articles.md
  docs/src/main/paradox/release-notes/1.0-M2.md
Labels: documentation

#1775 Update bots with new connectors
  .github/autolabeler.yml
  .github/release-drafter.yml
  .grenrc.js
Labels: alpakka-itself

#1771 sbt dynver 4.0.0
  project/plugins.sbt
Labels: alpakka-itself

#1772 AMQ: multiple hosts in AmqpDetailsConnectionProvider
  amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
Labels: p:amqp

#1778 Use latest scalafmt
  .scalafmt.conf
  project/plugins.sbt
Labels: alpakka-itself

#1780 Fix link in CSV release notes
  docs/src/main/paradox/release-notes/1.0.x/csv.md
Labels: documentation

#1784 Cache coursier data directory
  .travis.yml
Labels: alpakka-itself

#1783 Google Cloud Storage: application.conf path for config
  google-cloud-storage/src/test/resources/application.conf
Labels: p:google-cloud-storage

#1785 Fix Google Cloud Storage directory
  .github/autolabeler.yml
Labels: alpakka-itself

#1777 Override Jackson Databind dependency to 2.9.9
  project/Dependencies.scala
Labels: dependency-change, p:geode, p:json-streaming

#1680 Influxdb connector
  .travis.yml
  build.sbt
  docker-compose.yml
  docs/src/main/paradox/index.md
  docs/src/main/paradox/influxdb.md
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/InfluxDbReadSettings.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/InfluxDbWriteMessage.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/AlpakkaResultMapperHelper.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/InfluxDbFlowStage.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/InfluxDbSourceStage.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbFlow.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbSink.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbSource.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbFlow.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbSink.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbSource.scala
  influxdb/src/test/java/docs/javadsl/Cpu.java
  influxdb/src/test/java/docs/javadsl/InfluxDbCpu.java
  influxdb/src/test/java/docs/javadsl/InfluxDbSourceCpu.java
  influxdb/src/test/java/docs/javadsl/InfluxDbSourceTest.java
  influxdb/src/test/java/docs/javadsl/InfluxDbTest.java
  influxdb/src/test/java/docs/javadsl/TestConstants.java
  influxdb/src/test/java/docs/javadsl/TestUtils.java
  influxdb/src/test/scala/docs/scaladsl/FlowSpec.scala
  influxdb/src/test/scala/docs/scaladsl/InfluxDbFlowCpu.java
  influxdb/src/test/scala/docs/scaladsl/InfluxDbSourceCpu.java
  influxdb/src/test/scala/docs/scaladsl/InfluxDbSourceSpec.scala
  influxdb/src/test/scala/docs/scaladsl/InfluxDbSpec.scala
  influxdb/src/test/scala/docs/scaladsl/InfluxDbSpecCpu.java
  project/Dependencies.scala
  project/project-info.conf
Labels: dependency-change, documentation, p:influxdb, p:new

#1791 InfluxDB: API may change note
  docs/src/main/paradox/influxdb.md
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/InfluxDbReadSettings.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/InfluxDbWriteMessage.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/AlpakkaResultMapperHelper.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/InfluxDbFlowStage.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/InfluxDbSourceStage.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbFlow.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbSink.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbSource.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbFlow.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbSink.scala
  influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbSource.scala
  influxdb/src/test/java/docs/javadsl/InfluxDbCpu.java
  influxdb/src/test/java/docs/javadsl/InfluxDbTest.java
  influxdb/src/test/java/docs/javadsl/TestUtils.java
  influxdb/src/test/scala/docs/scaladsl/FlowSpec.scala
  influxdb/src/test/scala/docs/scaladsl/InfluxDbSpec.scala
  project/project-info.conf
Labels: documentation, p:influxdb

#1789 Describe versioning rules in docs
  docs/src/main/paradox/kinesis.md
  docs/src/main/paradox/other-docs/index.md
  docs/src/main/paradox/other-docs/versioning.md
  docs/src/main/paradox/release-notes/1.0.x.md
  docs/src/main/paradox/release-notes/index.md
  docs/src/main/paradox/solr.md
  project/plugins.sbt
Labels: documentation

#1746 Couchbase: Akka Discovery support
  couchbase/src/main/java/akka/stream/alpakka/couchbase/javadsl/DiscoverySupport.java
  couchbase/src/main/mima-filters/1.0.2.backwards.excludes
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/model.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSession.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/DiscoverySupport.scala
  couchbase/src/test/java/docs/javadsl/DiscoveryTest.java
  couchbase/src/test/resources/application.conf
  couchbase/src/test/resources/discovery.conf
  couchbase/src/test/scala/akka/stream/alpakka/couchbase/testing/CouchbaseSupport.scala
  couchbase/src/test/scala/docs/scaladsl/DiscoverySpec.scala
  docs/src/main/paradox/couchbase.md
  project/Dependencies.scala
Labels: dependency-change, documentation, p:couchbase
