Repository akka/alpakka, pull requests merged in 2019-07, with the labels that each got.

#1793 Fix HBase directory for auto labeling
  .github/autolabeler.yml
Labels: alpakka-itself

#1794 SQS: test against ElasticMQ native image
  docker-compose.yml
Labels: p:aws-sqs

#1796 SSE: Support gzip encoding
  sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
  sse/src/test/scala/docs/scaladsl/EventSourceSpec.scala
Labels: p:sse

#1577 MQTT streaming: SourceQueue backpressure
  mqtt-streaming/src/main/mima-filters/1.0.2.backwards.excludes
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/QueueOfferState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: p:mqtt-streaming

#1795 Issue 1786 - 'messageId' and 'publishTime' should not be published
  google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
  google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala
  google-cloud-pub-sub/src/test/java/docs/javadsl/ExampleUsageJava.java
  google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
  google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
  google-cloud-pub-sub/src/test/scala/docs/scaladsl/ExampleUsage.scala
Labels: p:google-cloud-pub-sub

#1799 Nightly with Akka 2.6
  mqtt/src/test/java/docs/javadsl/MqttFlowTest.java
  project/Dependencies.scala
Labels: alpakka-itself

#1803 Add java getter to Datagram
  udp/src/main/scala/akka/stream/alpakka/udp/model.scala
Labels: p:udp

#1804 Release notes 1.1.0
  .github/release-drafter.yml
  docs/src/main/paradox/other-docs/versioning.md
  docs/src/main/paradox/overview.md
  docs/src/main/paradox/release-notes/1.1.x.md
  docs/src/main/paradox/release-notes/1.1.x/amqp.md
  docs/src/main/paradox/release-notes/1.1.x/avroparquet.md
  docs/src/main/paradox/release-notes/1.1.x/awslambda.md
  docs/src/main/paradox/release-notes/1.1.x/azure-storage-queue.md
  docs/src/main/paradox/release-notes/1.1.x/cassandra.md
  docs/src/main/paradox/release-notes/1.1.x/couchbase.md
  docs/src/main/paradox/release-notes/1.1.x/csv.md
  docs/src/main/paradox/release-notes/1.1.x/dynamodb.md
  docs/src/main/paradox/release-notes/1.1.x/elasticsearch.md
  docs/src/main/paradox/release-notes/1.1.x/file.md
  docs/src/main/paradox/release-notes/1.1.x/ftp.md
  docs/src/main/paradox/release-notes/1.1.x/geode.md
  docs/src/main/paradox/release-notes/1.1.x/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/release-notes/1.1.x/google-cloud-pub-sub.md
  docs/src/main/paradox/release-notes/1.1.x/google-cloud-storage.md
  docs/src/main/paradox/release-notes/1.1.x/google-fcm.md
  docs/src/main/paradox/release-notes/1.1.x/hbase.md
  docs/src/main/paradox/release-notes/1.1.x/hdfs.md
  docs/src/main/paradox/release-notes/1.1.x/influxdb.md
  docs/src/main/paradox/release-notes/1.1.x/ironmq.md
  docs/src/main/paradox/release-notes/1.1.x/jms.md
  docs/src/main/paradox/release-notes/1.1.x/json-streaming.md
  docs/src/main/paradox/release-notes/1.1.x/kafka.md
  docs/src/main/paradox/release-notes/1.1.x/kinesis.md
  docs/src/main/paradox/release-notes/1.1.x/kudu.md
  docs/src/main/paradox/release-notes/1.1.x/mongodb.md
  docs/src/main/paradox/release-notes/1.1.x/mqtt-streaming.md
  docs/src/main/paradox/release-notes/1.1.x/mqtt.md
  docs/src/main/paradox/release-notes/1.1.x/orientdb.md
  docs/src/main/paradox/release-notes/1.1.x/s3.md
  docs/src/main/paradox/release-notes/1.1.x/simple-codecs.md
  docs/src/main/paradox/release-notes/1.1.x/slick.md
  docs/src/main/paradox/release-notes/1.1.x/sns.md
  docs/src/main/paradox/release-notes/1.1.x/solr.md
  docs/src/main/paradox/release-notes/1.1.x/spring-web.md
  docs/src/main/paradox/release-notes/1.1.x/sqs.md
  docs/src/main/paradox/release-notes/1.1.x/sse.md
  docs/src/main/paradox/release-notes/1.1.x/udp.md
  docs/src/main/paradox/release-notes/1.1.x/unix-domain-socket.md
  docs/src/main/paradox/release-notes/1.1.x/xml.md
  docs/src/main/paradox/release-notes/index.md
Labels: alpakka-itself, documentation

#1805 Google Cloud Storage: don't publish for Scala 2.11
  build.sbt
Labels: p:google-cloud-storage

#1806 Fix Akka 2.6 API usage
  .travis.yml
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  orientdb/src/test/java/docs/javadsl/OrientDbTest.java
Labels: p:mqtt-streaming, p:orientdb

#1808 Canonical URL fix
  project/Common.scala
Labels: documentation

#1813 Minor doc fixes
  docs/src/main/paradox/ftp.md
  docs/src/main/paradox/google-cloud-storage.md
Labels: documentation

#1809 Use JDK 11 when running nightly
  .travis.yml
Labels: alpakka-itself

#1814 Enable MiMa on Google Cloud Storage and InfluxDb
  build.sbt
Labels: p:google-cloud-storage, p:influxdb

#1812 Add imports to Ftp settings sample, actually run listFiles
  ftp/src/test/java/docs/javadsl/FtpTraversingExample.java
  ftp/src/test/java/docs/javadsl/FtpWritingTest.java
Labels: documentation, p:ftp

#1819 Move out Elasticsearch example to Alpakka-samples
  build.sbt
  doc-examples/src/main/java/elastic/FetchUsingSlickAndStreamIntoElasticInJava.java
  doc-examples/src/main/scala/elastic/FetchUsingSlickAndStreamIntoElastic.scala
  doc-examples/src/main/scala/playground/ElasticSearchEmbedded.scala
  doc-examples/src/main/scala/playground/elastic/ElasticsearchMock.scala
  docs/src/main/paradox/examples/elasticsearch-samples.md
  project/Dependencies.scala
Labels: alpakka-itself, dependency-change, documentation

#1818 Update to the latest Akka 2.6-M4
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/QueueOfferState.scala
  project/Dependencies.scala
Labels: alpakka-itself, dependency-change, p:mqtt-streaming

#1822 Solr: deleteByQuery with routing field
  solr/src/main/scala/akka/stream/alpakka/solr/impl/SolrFlowStage.scala
Labels: p:solr

#1823 mockito 3.0.0
  project/Dependencies.scala
Labels: dependency-change

#1807 Complete promise from the locally submitted ack
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: p:mqtt-streaming

#1828 Docs: fix links to 1.0.x release notes
  docs/src/main/paradox/release-notes/1.1.x/amqp.md
  docs/src/main/paradox/release-notes/1.1.x/avroparquet.md
  docs/src/main/paradox/release-notes/1.1.x/awslambda.md
  docs/src/main/paradox/release-notes/1.1.x/azure-storage-queue.md
  docs/src/main/paradox/release-notes/1.1.x/cassandra.md
  docs/src/main/paradox/release-notes/1.1.x/couchbase.md
  docs/src/main/paradox/release-notes/1.1.x/csv.md
  docs/src/main/paradox/release-notes/1.1.x/dynamodb.md
  docs/src/main/paradox/release-notes/1.1.x/elasticsearch.md
  docs/src/main/paradox/release-notes/1.1.x/file.md
  docs/src/main/paradox/release-notes/1.1.x/ftp.md
  docs/src/main/paradox/release-notes/1.1.x/geode.md
  docs/src/main/paradox/release-notes/1.1.x/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/release-notes/1.1.x/google-cloud-pub-sub.md
  docs/src/main/paradox/release-notes/1.1.x/google-fcm.md
  docs/src/main/paradox/release-notes/1.1.x/hbase.md
  docs/src/main/paradox/release-notes/1.1.x/hdfs.md
  docs/src/main/paradox/release-notes/1.1.x/ironmq.md
  docs/src/main/paradox/release-notes/1.1.x/jms.md
  docs/src/main/paradox/release-notes/1.1.x/json-streaming.md
  docs/src/main/paradox/release-notes/1.1.x/kinesis.md
  docs/src/main/paradox/release-notes/1.1.x/kudu.md
  docs/src/main/paradox/release-notes/1.1.x/mongodb.md
  docs/src/main/paradox/release-notes/1.1.x/mqtt-streaming.md
  docs/src/main/paradox/release-notes/1.1.x/mqtt.md
  docs/src/main/paradox/release-notes/1.1.x/orientdb.md
  docs/src/main/paradox/release-notes/1.1.x/s3.md
  docs/src/main/paradox/release-notes/1.1.x/simple-codecs.md
  docs/src/main/paradox/release-notes/1.1.x/slick.md
  docs/src/main/paradox/release-notes/1.1.x/sns.md
  docs/src/main/paradox/release-notes/1.1.x/solr.md
  docs/src/main/paradox/release-notes/1.1.x/spring-web.md
  docs/src/main/paradox/release-notes/1.1.x/sqs.md
  docs/src/main/paradox/release-notes/1.1.x/sse.md
  docs/src/main/paradox/release-notes/1.1.x/udp.md
  docs/src/main/paradox/release-notes/1.1.x/unix-domain-socket.md
  docs/src/main/paradox/release-notes/1.1.x/xml.md
Labels: documentation

#1842 Update to Akka 2.6.0-M5
  project/Dependencies.scala
Labels: alpakka-itself, dependency-change

#1841 Update to Alpakka Kafka
  project/Dependencies.scala
Labels: alpakka-itself, dependency-change

#1832 mqtt-streaming: Partially revert #1818
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/QueueOfferState.scala
Labels: p:mqtt-streaming

#1848 Spawn MQTT connector actors as system actors
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
Labels: p:mqtt-streaming

#1849 Make typed/untyped MqttFlowSpec independent
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
  mqtt/src/test/travis/acl
Labels: p:mqtt, p:mqtt-streaming
