Repository akka/alpakka, pull requests merged in 2019-05, with the labels that each got.

#1666 Docs: Add blog and presentation to list
  docs/src/main/paradox/other-docs/webinars-presentations-articles.md
Labels: alpakka-itself

#1674 Alpakka Kafka 1.0.2
  project/Dependencies.scala
Labels: alpakka-itself

#1678 Align local date in s3 stream signing key to UTC
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
Labels: p:aws-s3

#1671 FTP: support partial file download
  ftp/src/main/scala/akka/stream/alpakka/ftp/impl/CommonFtpOperations.scala
  ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
  ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
  ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
  ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
  ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
  ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
  ftp/src/test/java/akka/stream/alpakka/ftp/StrictHostCheckingSftpSourceTest.java
  ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
  ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
  ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
  ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
  ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
Labels: p:ftp

#1677 Couchbase: reuse `AsyncCluster` via registry
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseClusterRegistry.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseSession.scala
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSession.scala
  couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
  couchbase/src/test/scala/docs/scaladsl/CouchbaseSessionExamplesSpec.scala
  couchbase/src/test/scala/docs/scaladsl/CouchbaseSourceSpec.scala
  docs/src/main/paradox/couchbase.md
Labels: p:couchbase

#1681 SQS/SNS: Update aws-spi-akka-http to version 0.0.6
  project/Dependencies.scala
Labels: p:aws-sns, p:aws-sqs

#1608 S3: Bucket management
  docs/src/main/paradox/s3.md
  s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
  s3/src/main/scala/akka/stream/alpakka/s3/model.scala
  s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
  s3/src/test/java/docs/javadsl/S3Test.java
  s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
  s3/src/test/scala/docs/scaladsl/S3SourceSpec.scala
Labels: p:aws-s3

#1639 AWS S3 - forward proxy support
  s3/src/main/mima-filters/1.0.0.backwards.excludes
  s3/src/main/resources/reference.conf
  s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
  s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ExtSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
Labels: p:aws-s3

#1684 S3: Broken bucket naming rules link
  docs/src/main/paradox/s3.md
  s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
Labels: p:aws-s3

#1686 AWS S3: use a single date/time for signing
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/Signer.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/SigningKey.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SignerSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SigningKeySpec.scala
Labels: p:aws-s3

#1687 Alpakka Kafka 1.0.3
  project/Dependencies.scala
Labels: documentation

#1685 Add alpakka-csv benchmark and optimize.
  build.sbt
  csv-bench/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvBench.scala
  csv/src/main/mima-filters/1.0.x.backwards.excludes
  csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
Labels: p:csv

#1689 Mongo DB: Add missing imports to docs.
  mongodb/src/test/scala/docs/scaladsl/MongoSourceSpec.scala
Labels: p:mongodb

#1688 Sync grpc version to the one that comes from akka-grpc
  project/Dependencies.scala
Labels: p:google-cloud-pub-sub-grpc

#1696 SQS source: make parallelism configurable
  docs/src/main/paradox/sqs.md
  sqs/src/main/mima-filters/1.0.x.backwards.excludes
  sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
  sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
  sqs/src/test/java/docs/javadsl/SqsPublishTest.java
  sqs/src/test/java/docs/javadsl/SqsSourceTest.java
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Labels: p:aws-sqs

#1673 SOLR: Exclude message with PassThrough
  docs/src/main/paradox/solr.md
  solr/src/main/scala/akka/stream/alpakka/solr/SolrMessages.scala
  solr/src/main/scala/akka/stream/alpakka/solr/impl/SolrFlowStage.scala
  solr/src/test/java/docs/javadsl/SolrTest.java
  solr/src/test/scala/docs/scaladsl/SolrSpec.scala
Labels: p:solr

#1699 PassThroughFlow examples in Java
  doc-examples/src/test/java/akka/stream/alpakka/eip/javadsl/PassThroughExamples.java
  docs/src/main/paradox/patterns.md
Labels: documentation

#1700 AWS SDK 2.5.20 -> 2.5.41
  project/Dependencies.scala
Labels: dependency-change, p:aws-lambda, p:aws-sns, p:aws-sqs

#1695 AWS SQS/SNS: more concise docs about the HTTP client
  build.sbt
  docs/src/main/paradox/sns.md
  docs/src/main/paradox/sqs.md
  sns/src/test/java/docs/javadsl/SnsPublisherTest.java
  sns/src/test/scala/akka/stream/alpakka/sns/IntegrationTestContext.scala
  sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
  sqs/src/test/java/docs/javadsl/SqsSourceTest.java
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
  sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Labels: p:aws-sns, p:aws-sqs

#1644 Read from Kafka write to Elasticsearch example
  doc-examples/src/main/java/elastic/KafkaToElasticInJava.java
  doc-examples/src/main/java/ftpsamples/FtpToFileExample.java
  doc-examples/src/main/resources/logback.xml
  doc-examples/src/main/scala/elastic/KafkaToElastic.scala
  docs/src/main/paradox/examples/elasticsearch-samples.md
  project/Dependencies.scala
Labels: documentation, p:elasticsearch

#1703 Fix: LogRotatorSink does not complete when consuming an empty source
  file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
  file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
Labels: p:file

#1604 SQS: Revise stream element data model
  docs/src/main/paradox/sqs.md
  sqs/src/main/mima-filters/1.0.0.backwards.excludes
  sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckFlow.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala
  sqs/src/test/java/docs/javadsl/SqsAckTest.java
  sqs/src/test/java/docs/javadsl/SqsPublishTest.java
  sqs/src/test/scala/akka/stream/alpakka/sqs/SqsModelSpec.scala
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
Labels: api-change, p:aws-sqs

#1702 Release notes 1.0.1
  docs/src/main/paradox/release-notes/1.0.x.md
  docs/src/main/paradox/release-notes/1.0.x/amqp.md
  docs/src/main/paradox/release-notes/1.0.x/avroparquet.md
  docs/src/main/paradox/release-notes/1.0.x/awslambda.md
  docs/src/main/paradox/release-notes/1.0.x/azure-storage-queue.md
  docs/src/main/paradox/release-notes/1.0.x/cassandra.md
  docs/src/main/paradox/release-notes/1.0.x/couchbase.md
  docs/src/main/paradox/release-notes/1.0.x/csv.md
  docs/src/main/paradox/release-notes/1.0.x/dynamodb.md
  docs/src/main/paradox/release-notes/1.0.x/elasticsearch.md
  docs/src/main/paradox/release-notes/1.0.x/file.md
  docs/src/main/paradox/release-notes/1.0.x/ftp.md
  docs/src/main/paradox/release-notes/1.0.x/geode.md
  docs/src/main/paradox/release-notes/1.0.x/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/release-notes/1.0.x/google-cloud-pub-sub.md
  docs/src/main/paradox/release-notes/1.0.x/google-fcm.md
  docs/src/main/paradox/release-notes/1.0.x/hbase.md
  docs/src/main/paradox/release-notes/1.0.x/hdfs.md
  docs/src/main/paradox/release-notes/1.0.x/ironmq.md
  docs/src/main/paradox/release-notes/1.0.x/jms.md
  docs/src/main/paradox/release-notes/1.0.x/json-streaming.md
  docs/src/main/paradox/release-notes/1.0.x/kinesis.md
  docs/src/main/paradox/release-notes/1.0.x/kudu.md
  docs/src/main/paradox/release-notes/1.0.x/mongodb.md
  docs/src/main/paradox/release-notes/1.0.x/mqtt-streaming.md
  docs/src/main/paradox/release-notes/1.0.x/mqtt.md
  docs/src/main/paradox/release-notes/1.0.x/orientdb.md
  docs/src/main/paradox/release-notes/1.0.x/s3.md
  docs/src/main/paradox/release-notes/1.0.x/simple-codecs.md
  docs/src/main/paradox/release-notes/1.0.x/slick.md
  docs/src/main/paradox/release-notes/1.0.x/sns.md
  docs/src/main/paradox/release-notes/1.0.x/solr.md
  docs/src/main/paradox/release-notes/1.0.x/spring-web.md
  docs/src/main/paradox/release-notes/1.0.x/sqs.md
  docs/src/main/paradox/release-notes/1.0.x/sse.md
  docs/src/main/paradox/release-notes/1.0.x/udp.md
  docs/src/main/paradox/release-notes/1.0.x/unix-domain-socket.md
  docs/src/main/paradox/release-notes/1.0.x/xml.md
Labels: alpakka-itself

#1708 Migrate to publish rsync plugin
  project/PublishRsync.scala
  project/plugins.sbt
Labels: alpakka-itself

#1704 AWS SDK 2.5.44
  project/Dependencies.scala
Labels: dependency-change, p:aws-sns, p:aws-sqs

#1709 AWS Sqs: fix Scaladoc links after rename
  docs/src/main/paradox/sqs.md
Labels: p:aws-sqs

#1711 CSV: stream may end with delimiter
  csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
  csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
  csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
Labels: p:csv

#1721 MQTT streaming: correct deprecated since version
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/javadsl/Mqtt.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
Labels: p:mqtt-streaming

#1707 Whitesource reporting: separate report for supported modules
  .travis.yml
  build.sbt
  docs/release-train-issue-template.md
Labels: alpakka-itself

#1722 DynamoDb: set port from settings even when tls=true
  dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
Labels: p:dynamodb

#1724 DynamoDb: set 443 as default port
  dynamodb/src/main/resources/reference.conf
Labels: p:dynamodb

#1717 CSV: accept escape without escapeable byte after
  csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
  csv/src/test/java/docs/javadsl/CsvFormattingTest.java
  csv/src/test/java/docs/javadsl/CsvParsingTest.java
  csv/src/test/java/docs/javadsl/CsvToMapTest.java
  csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
  csv/src/test/scala/docs/scaladsl/CsvFormattingSpec.scala
  docs/src/main/paradox/data-transformations/csv.md
Labels: p:csv

#1726 Standardise extref names
  build.sbt
  docs/src/main/paradox/amqp.md
  docs/src/main/paradox/cassandra.md
  docs/src/main/paradox/data-transformations/compression.md
  docs/src/main/paradox/data-transformations/json.md
  docs/src/main/paradox/data-transformations/parsing-lines.md
  docs/src/main/paradox/examples/csv-samples.md
  docs/src/main/paradox/mongodb.md
  docs/src/main/paradox/overview.md
  docs/src/main/paradox/patterns.md
  docs/src/main/paradox/sns.md
  docs/src/main/paradox/sqs.md
Labels: alpakka-itself

#1729 Remove external couchbase page
  docs/src/main/paradox/external/couchbase.md
Labels: documentation

#1731 Upgrade to the latest scalafmt 2.0.0-RC7 / sbt-scalafmt 2.0.0
  .scalafmt.conf
  .travis.yml
  build.sbt
  csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
  doc-examples/src/main/scala/ftpsamples/RotateLogsToFtp.scala
  dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/AwsClient.scala
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
  file/src/main/scala/akka/stream/alpakka/file/javadsl/LogRotatorSink.scala
  file/src/main/scala/akka/stream/alpakka/file/scaladsl/Directory.scala
  file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/PubSubSettings.scala
  google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmFlows.scala
  jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
  jms/src/test/scala/docs/scaladsl/JmsBufferedAckConnectorsSpec.scala
  jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
  jms/src/test/scala/docs/scaladsl/JmsTxConnectorsSpec.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
  mqtt/src/main/scala/akka/stream/alpakka/mqtt/impl/MqttFlowStage.scala
  mqtt/src/test/scala/docs/scaladsl/MqttSourceSpec.scala
  project/Common.scala
  project/Dependencies.scala
  project/TestChanged.scala
  project/Whitesource.scala
  project/plugins.sbt
  s3/src/main/scala/akka/stream/alpakka/s3/S3Headers.scala
  s3/src/main/scala/akka/stream/alpakka/s3/headers/ServerSideEncryption.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/DiskBuffer.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  simple-codecs/src/test/scala/docs/scaladsl/RecordIOFramingSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
  unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/impl/UnixDomainSocketImpl.scala
Labels: alpakka-itself

#1734 S3: Move FailedUpload exception to the user facing API
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/main/scala/akka/stream/alpakka/s3/model.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
  s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
Labels: p:aws-s3

#1730 Finish move of CSV example; use Committer in pass-through examples
  doc-examples/src/main/java/csvsamples/FetchHttpEvery30SecondsAndConvertCsvToJsonToKafkaInJava.java
  doc-examples/src/main/scala/csvsamples/FetchHttpEvery30SecondsAndConvertCsvToJsonToKafka.scala
  doc-examples/src/main/scala/playground/KafkaEmbedded.scala
  doc-examples/src/test/java/akka/stream/alpakka/eip/javadsl/PassThroughExamples.java
  doc-examples/src/test/scala/akka/stream/alpakka/eip/scaladsl/PassThroughExamples.scala
  docs/src/main/paradox/.htaccess
  docs/src/main/paradox/examples/csv-samples.md
  docs/src/main/paradox/examples/index.md
  project/Dependencies.scala
Labels: documentation

#1737 Release notes 1.0.2
  docs/src/main/paradox/release-notes/1.0.x.md
  docs/src/main/paradox/release-notes/1.0.x/avroparquet.md
  docs/src/main/paradox/release-notes/1.0.x/awslambda.md
  docs/src/main/paradox/release-notes/1.0.x/azure-storage-queue.md
  docs/src/main/paradox/release-notes/1.0.x/cassandra.md
  docs/src/main/paradox/release-notes/1.0.x/couchbase.md
  docs/src/main/paradox/release-notes/1.0.x/csv.md
  docs/src/main/paradox/release-notes/1.0.x/dynamodb.md
  docs/src/main/paradox/release-notes/1.0.x/elasticsearch.md
  docs/src/main/paradox/release-notes/1.0.x/file.md
  docs/src/main/paradox/release-notes/1.0.x/ftp.md
  docs/src/main/paradox/release-notes/1.0.x/geode.md
  docs/src/main/paradox/release-notes/1.0.x/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/release-notes/1.0.x/google-cloud-pub-sub.md
  docs/src/main/paradox/release-notes/1.0.x/google-fcm.md
  docs/src/main/paradox/release-notes/1.0.x/hbase.md
  docs/src/main/paradox/release-notes/1.0.x/hdfs.md
  docs/src/main/paradox/release-notes/1.0.x/ironmq.md
  docs/src/main/paradox/release-notes/1.0.x/jms.md
  docs/src/main/paradox/release-notes/1.0.x/json-streaming.md
  docs/src/main/paradox/release-notes/1.0.x/kinesis.md
  docs/src/main/paradox/release-notes/1.0.x/kudu.md
  docs/src/main/paradox/release-notes/1.0.x/mongodb.md
  docs/src/main/paradox/release-notes/1.0.x/mqtt-streaming.md
  docs/src/main/paradox/release-notes/1.0.x/mqtt.md
  docs/src/main/paradox/release-notes/1.0.x/orientdb.md
  docs/src/main/paradox/release-notes/1.0.x/s3.md
  docs/src/main/paradox/release-notes/1.0.x/simple-codecs.md
  docs/src/main/paradox/release-notes/1.0.x/slick.md
  docs/src/main/paradox/release-notes/1.0.x/sns.md
  docs/src/main/paradox/release-notes/1.0.x/solr.md
  docs/src/main/paradox/release-notes/1.0.x/spring-web.md
  docs/src/main/paradox/release-notes/1.0.x/sqs.md
  docs/src/main/paradox/release-notes/1.0.x/sse.md
  docs/src/main/paradox/release-notes/1.0.x/udp.md
  docs/src/main/paradox/release-notes/1.0.x/unix-domain-socket.md
  docs/src/main/paradox/release-notes/1.0.x/xml.md
Labels: alpakka-itself

#1736 Add Release Drafter config
  .github/release-drafter.yml
Labels: alpakka-itself
