Repository akka/alpakka, pull requests merged in 2020-09, with the labels that each got.

#2382 Check client instance for nulls
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
  kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
  kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSource.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttActorSystemsSpec.scala
  sns/src/main/scala/akka/stream/alpakka/sns/scaladsl/SnsPublisher.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
Labels: p:aws-sns, p:aws-sqs, p:elasticsearch, p:kinesis, p:mqtt-streaming

#2312 Update Akka gRPC to use native openssl
  build.sbt
  docs/src/main/paradox/google-cloud-pub-sub-grpc.md
  google-cloud-pub-sub-grpc/src/main/mima-filters/2.0.1.backwards.excludes/settings.backwards.excludes
  google-cloud-pub-sub-grpc/src/main/resources/reference.conf
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/PubSubSettings.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/impl/AkkaGrpcSettings.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GrpcPublisher.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GrpcSubscriber.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GrpcPublisher.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GrpcSubscriber.scala
  google-cloud-pub-sub-grpc/src/test/resources/application.conf
  project/Dependencies.scala
  project/plugins.sbt
Labels: dependency-change, documentation, p:google-cloud-pub-sub-grpc

#2390 SQS tests: Remove tight requestNext timeout
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceMockSpec.scala
Labels: p:aws-sqs

#2393 Build against Akka 2.6.8 on Travis nightlies
  project/Dependencies.scala
Labels: dependency-change

#2392 S3: Add access-style property
  s3/src/main/resources/reference.conf
  s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
  s3/src/main/scala/akka/stream/alpakka/s3/model.scala
  s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
  s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ExtSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Labels: p:aws-s3

#2286 Scala to 2.12.11 and 2.13.2 and silencer 1.7.0
  .travis.yml
  project/Dependencies.scala
Labels: dependency-change

#2395 S3: `text/event-stream` ContentType in multipart upload response
  s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/MarshallingSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SlowMinioIntegrationSpec.scala
  scripts/create-slow-minio.sh
Labels: p:aws-s3

#2397 docs: least Akka 2.6 version from the scheduled build
  docs/src/main/paradox/overview.md
Labels: documentation

#2404 File: tar with directory support and EOF block detection
  docs/src/main/paradox/file.md
  file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntry.scala
  file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarReaderStage.scala
  file/src/main/scala/akka/stream/alpakka/file/model.scala
  file/src/test/java/docs/javadsl/ArchiveTest.java
  file/src/test/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntrySpec.scala
  file/src/test/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlowTest.scala
  file/src/test/scala/docs/scaladsl/TarArchiveSpec.scala
Labels: documentation, p:file

#2398 doc: Alpakka Kafka 2.0.5 in the patterns section
  doc-examples/src/test/scala/akka/stream/alpakka/eip/scaladsl/PassThroughExamples.scala
  project/Dependencies.scala
Labels: dependency-change, documentation

#2405 Add BigQuery to the release drafter template
  .github/release-drafter.yml
Labels: p:google-cloud-bigquery

#2408 JMS: accept Float as properties and map values
  jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsMessageProducer.scala
  jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
Labels: p:jms

#2411 tests: disable parallel execution
  build.sbt
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: alpakka-itself, p:mqtt-streaming

#2412 sbt 1.13.3, latest JDKs, latest test libs, fewer CI steps
  .travis.yml
  project/Dependencies.scala
  project/build.properties
  scripts/build.sh
Labels: dependency-change

#2402 Geode: Apache Geode 1.13.0 (was 1.12.0)
  docker-compose.yml
  project/Dependencies.scala
Labels: dependency-change, p:geode

#2406 S3: Add method to delete bucket contents
  s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
  s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
Labels: p:aws-s3

#2413 Less use of deprecated APIs in Java code
  amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectionProvidersTest.java
  aws-event-bridge/src/test/java/docs/javadsl/EventBridgePublisherTest.java
  build.sbt
  couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
  couchbase/src/test/java/docs/javadsl/DiscoveryTest.java
  csv/src/test/java/docs/javadsl/CsvFormattingTest.java
  csv/src/test/java/docs/javadsl/CsvParsingTest.java
  csv/src/test/java/docs/javadsl/CsvToMapTest.java
  file/src/test/scala/docs/scaladsl/TarArchiveSpec.scala
  ftp/src/test/java/docs/javadsl/FtpWritingTest.java
  google-cloud-storage/src/test/java/docs/javadsl/GCStorageTest.java
  jms/src/test/java/docs/javadsl/JmsSettingsTest.java
  jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
  json-streaming/src/test/java/docs/javadsl/JsonReaderUsageTest.java
  kudu/src/test/java/docs/javadsl/KuduTableTest.java
  mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
  mqtt/src/test/java/docs/javadsl/MqttSourceTest.java
  project/Common.scala
  simple-codecs/src/test/java/docs/javadsl/RecordIOFramingTest.java
  slick/src/test/java/docs/javadsl/SlickTest.java
  sns/src/test/java/docs/javadsl/SnsPublisherTest.java
  text/src/test/java/docs/javadsl/CharsetCodingFlowsDoc.java
  xml/src/test/java/docs/javadsl/XmlParsingTest.java
Labels: p:amqp, p:aws-event-bridge, p:aws-sns, p:couchbase, p:csv, p:file, p:ftp, p:google-cloud-storage, p:jms, p:json-streaming, p:kudu, p:mqtt, p:mqtt-streaming, p:recordio, p:slick, p:text, p:xml

#2414 Patch version upgrades accross the board
  project/Dependencies.scala
Labels: dependency-change

#2416 Cassandra: overwrite Netty to 4.1.52
  project/Dependencies.scala
Labels: dependency-change, p:cassandra

#2403 Google Cloud Pub/Sub: use SingleRequest
  google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
Labels: p:google-cloud-pub-sub

#2388 Make GCS md5Hash optional
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/Formats.scala
  google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/scaladsl/GCStorageWiremockBase.scala
Labels: p:google-cloud-storage

#2417 2.0.2 Release Notes
  docs/release-train-issue-template.md
  docs/src/main/paradox/release-notes/2.0.x.md
  docs/src/main/paradox/release-notes/2.0.x/amqp.md
  docs/src/main/paradox/release-notes/2.0.x/aws-event-bridge.md
  docs/src/main/paradox/release-notes/2.0.x/cassandra.md
  docs/src/main/paradox/release-notes/2.0.x/elasticsearch.md
  docs/src/main/paradox/release-notes/2.0.x/file.md
  docs/src/main/paradox/release-notes/2.0.x/geode.md
  docs/src/main/paradox/release-notes/2.0.x/google-cloud-bigquery.md
  docs/src/main/paradox/release-notes/2.0.x/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/release-notes/2.0.x/google-cloud-pub-sub.md
  docs/src/main/paradox/release-notes/2.0.x/google-cloud-storage.md
  docs/src/main/paradox/release-notes/2.0.x/jms.md
  docs/src/main/paradox/release-notes/2.0.x/json-streaming.md
  docs/src/main/paradox/release-notes/2.0.x/kinesis.md
  docs/src/main/paradox/release-notes/2.0.x/mqtt-streaming.md
  docs/src/main/paradox/release-notes/2.0.x/pravega.md
  docs/src/main/paradox/release-notes/2.0.x/s3.md
  docs/src/main/paradox/release-notes/2.0.x/slick.md
  docs/src/main/paradox/release-notes/2.0.x/sns.md
  docs/src/main/paradox/release-notes/2.0.x/sqs.md
Labels: documentation

#2421 FTP test: use all stages stopped timeout
  ftp/src/test/resources/application.conf
  ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
  ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
Labels: p:ftp

#2420 Google Cloud Pub/Sub gRPC: align the gRPC auth version
  project/Dependencies.scala
Labels: dependency-change, p:google-cloud-pub-sub-grpc

#2426 Google Pub/Sub gRPC: use the gcloud emulator in tests
  docker-compose.yml
Labels: p:google-cloud-pub-sub-grpc

#2425 Google Pub/Sub: tests using the gcloud emulator
  .travis.yml
  build.sbt
  google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/javadsl/GooglePubSub.scala
  google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/scaladsl/GooglePubSub.scala
  google-cloud-pub-sub/src/test/scala/docs/scaladsl/IntegrationSpec.scala
Labels: p:google-cloud-pub-sub

#2427 Inherit io.grpc version from Akka gRPC
  project/Dependencies.scala
Labels: dependency-change, p:google-cloud-pub-sub-grpc

#2422 Google Cloud Pub/Sub gRPC: acknowledge flow
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GooglePubSub.scala
  google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GooglePubSub.scala
  google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
Labels: dependency-change, p:google-cloud-pub-sub-grpc
