Repository akka/alpakka, pull requests merged in 2020-08, with the labels that each got.

#2362 AWS S3: Avoid uploading a empty chunk after splitting
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Labels: p:aws-s3

#2369 Akka HTTP 10.2 RC2 in the scheduled build
  project/Dependencies.scala
Labels: dependency-change

#2371 AMQP: Fixes handling null replyTo header in AmqpReplyToSinkStage
  amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpReplyToSinkStage.scala
  amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
Labels: p:amqp

#2373 Jackson 2.10.5 (to get latest security fixes)
  project/Dependencies.scala
Labels: dependency-change

#2374 Akka HTTP 10.2 in the scheduled build
  project/Dependencies.scala
Labels: dependency-change

#2375 docs: Spelling
  docs/src/main/paradox/patterns.md
Labels: documentation

#2381 BigQuery: re-implement splitter as stage
  google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/impl/util/Delay.scala
  google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/impl/util/Splitter.scala
  google-cloud-bigquery/src/test/scala/akka/stream/alpakka/googlecloud/bigquery/impl/util/SplitterSpec.scala
Labels: p:google-cloud-bigquery

#2387 Fix Elasticsearch WriteMessage.createIndexMessage documentation
  docs/src/main/paradox/elasticsearch.md
Labels: documentation

#2377 Kinesis KCL source backpressure
  kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSchedulerSourceStage.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesis/DefaultTestContext.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSchedulerSourceSpec.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesis/Valve.scala
Labels: p:kinesis
