Repository akka/alpakka, pull requests merged in 2021-04, with the labels that each got.

#2638 ⬆️ Geode 1.13.2
  docker-compose.yml
  project/Dependencies.scala
Labels: dependency-change, p:geode

#2646 Migrate to sonatype snapshot/release repositories
  .travis.yml
  .travis/travis_gpg_secret.enc
  build.sbt
  docs/release-train-issue-template.md
  docs/src/main/paradox/other-docs/snapshots.md
  docs/src/main/paradox/other-docs/versioning.md
  project/Publish.scala
  project/plugins.sbt
Labels: documentation

#2639 Google Common: Fix authorization error
  google-common/src/main/scala/akka/stream/alpakka/google/auth/AccessToken.scala
Labels: p:google-common

#2641 Google: Drop old jwt-core dependencies
  project/Dependencies.scala
Labels: dependency-change, p:google-cloud-bigquery, p:google-cloud-pub-sub, p:google-cloud-storage, p:google-fcm

#2658 Fixed empty source XML parsing #2655
  xml/src/main/scala/akka/stream/alpakka/xml/impl/StreamingXmlParser.scala
  xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlParsing.scala
  xml/src/test/scala/docs/scaladsl/XmlProcessingSpec.scala
Labels: p:xml
