Repository akka/alpakka, pull requests merged in 2022-09, with the labels that each got.

#2896 Google PubSub gRPC and BigQuery Storage: Akka gRPC 2.1.5
  project/plugins.sbt
Labels: p:google-cloud-pub-sub-grpc, p:google-cloud-bigquery-storage

#2909 Update to Slick 3.4.1
  project/Dependencies.scala
Labels: p:slick, dependency-change

#2908 Update Jackson dependency to 2.13.4
  project/Dependencies.scala
Labels: alpakka-itself, dependency-change

#2907 Update Spring dependency
  project/Dependencies.scala
Labels: p:spring-web, dependency-change

#2916 Update Hadoop dependency to 3.3.3
  project/Dependencies.scala
Labels: dependency-change

#2918 Update solrj dependency to 8.11.1
  project/Dependencies.scala
  solr/src/main/scala/akka/stream/alpakka/solr/impl/SolrFlowStage.scala
  solr/src/test/java/docs/javadsl/SolrTest.java
  solr/src/test/scala/docs/scaladsl/SolrSpec.scala
Labels: p:solr, dependency-change

#2919 Update hadoop to 3.3.3
  project/Dependencies.scala
Labels: dependency-change

#2920 Update Cassandra driver to 4.14.1
  project/Dependencies.scala
Labels: dependency-change
