Repository akka/alpakka, pull requests merged in 2022-10, with the labels that each got.

#2921 Update Akka to 2.7.0-M2
  amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
  amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpFlowTest.java
  amqp/src/test/java/docs/javadsl/AmqpDocsTest.java
  amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
  amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpFlowSpec.scala
  amqp/src/test/scala/docs/scaladsl/AmqpDocsSpec.scala
  avroparquet/src/test/scala/docs/scaladsl/AvroParquetSourceSpec.scala
  aws-event-bridge/src/test/scala/akka/stream/alpakka/aws/eventbridge/EventBridgePublishMockSpec.scala
  awslambda/src/test/scala/docs/scaladsl/AwsLambdaFlowSpec.scala
  cassandra/src/test/scala/docs/javadsl/CassandraSessionSpec.scala
  csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
  elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStageTest.scala
  elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourcStageTest.scala
  file/src/test/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlowTest.scala
  file/src/test/scala/docs/scaladsl/FileTailSourceExtrasSpec.scala
  file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
  ftp/src/test/java/akka/stream/alpakka/ftp/CommonFtpStageTest.java
  ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
  google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/javadsl/jackson/BigQueryMarshallers.scala
  google-cloud-pub-sub/src/test/scala/docs/scaladsl/IntegrationSpec.scala
  google-common/src/test/scala/akka/stream/alpakka/google/util/AnnotateLastSpec.scala
  jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
  jms/src/test/scala/docs/scaladsl/JmsBufferedAckConnectorsSpec.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisFlowSpec.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSchedulerSourceSpec.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSourceSpec.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesisfirehose/KinesisFirehoseFlowSpec.scala
  mqtt-streaming/src/test/scala/akka/stream/alpakka/mqtt/streaming/impl/MqttFrameStageSpec.scala
  mqtt/src/test/java/docs/javadsl/MqttSourceTest.java
  mqtt/src/test/scala/docs/scaladsl/MqttSourceSpec.scala
  project/Dependencies.scala
  sns/src/test/scala/akka/stream/alpakka/sns/SnsPublishMockingSpec.scala
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceMockSpec.scala
  text/src/test/scala/akka/stream/alpakka/text/scaladsl/CharsetCodingFlowsSpec.scala
  udp/src/test/java/docs/javadsl/UdpTest.java
  udp/src/test/scala/docs/scaladsl/UdpSpec.scala
Labels: p:ftp, p:amqp, p:mqtt, p:kinesis, p:jms, p:google-cloud-pub-sub, p:elasticsearch, p:cassandra, p:csv, p:file, p:aws-lambda, p:avroparquet, p:mqtt-streaming, dependency-change, p:aws-event-bridge, p:google-cloud-bigquery, p:google-common

#2923 Cassandra: pick current Jackson version
  project/Dependencies.scala
Labels: p:cassandra, dependency-change

#2924 bump: Jackson databind 2.13.4.1
  project/Dependencies.scala
Labels: dependency-change

#2927 bump: sbt 1.7.2 and plugins (Akka gRPC 2.2.0-M1)
  google-cloud-pub-sub-grpc/src/main/mima-filters/5.0.0-M1.backwards.excludes/grpc2.backwards.excludes
  project/build.properties
  project/plugins.sbt
Labels: p:google-cloud-pub-sub-grpc

#2925 bump: Scala 2.13.10 and 2.12.17; Javadoc links
  amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpGraphStageLogicConnectionShutdownSpec.scala
  build.sbt
  csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
  docs/src/main/paradox/ftp.md
  docs/src/main/paradox/google-cloud-bigquery.md
  docs/src/main/paradox/jms/producer.md
  google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
  influxdb/src/test/scala/docs/scaladsl/InfluxDbSourceSpec.scala
  ironmq/src/main/scala/akka/stream/alpakka/ironmq/scaladsl/IronMqProducer.scala
  jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
  kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/KinesisTest.java
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
  pravega/src/main/scala/akka/stream/alpakka/pravega/scaladsl/Pravega.scala
  pravega/src/main/scala/akka/stream/alpakka/pravega/scaladsl/PravegaTable.scala
  project/Common.scala
  project/Dependencies.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/SplitAfterSize.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/SplitAfterSizeWithContext.scala
  s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
  s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ExtSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
  scripts/link-validator.conf
Labels: p:aws-s3, p:amqp, p:kinesis, p:jms, p:google-cloud-pub-sub, p:csv, p:ironmq, p:mqtt-streaming, dependency-change, documentation, p:influxdb, p:pravega

#2929 Update Akka dependencies
  project/Dependencies.scala
  project/plugins.sbt
Labels: dependency-change

#2931 Update to Akka 2.7.0, Akka HTTP 10.4.0
  docs/src/main/paradox/release-notes/5.0.x.md
  docs/src/main/paradox/release-notes/index.md
  project/Dependencies.scala
  project/plugins.sbt
Labels: dependency-change, documentation
