Repository akka/alpakka, pull requests merged in 2022-04, with the labels that each got.

#2849 chore: update sbt plugins
  project/plugins.sbt
Labels: alpakka-itself

#2848 Couchbase: retract supported level
  project/project-info.conf
Labels: p:couchbase

#2678 Google PubSub gRPC and BigQuery Storage: Akka gRPC 2.1.4
  build.sbt
  google-cloud-pub-sub-grpc/src/main/mima-filters/4.0.0.backwards.excludes/grpc2.backwards.excludes
  project/Dependencies.scala
  project/plugins.sbt
Labels: p:google-cloud-pub-sub-grpc, dependency-change, p:google-cloud-bigquery-storage

#2856 Remove S3 depreciations
  s3/src/main/mima-filters/4.0.0-M1.backwards.excludes/pr-2856-alpakka-3-deprecations.backwards.excludes
  s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
  s3/src/main/scala/akka/stream/alpakka/s3/model.scala
  s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
Labels: p:aws-s3

#2862 Pravega 0.10.2 (was 0.10.1)
  docker-compose.yml
  project/Dependencies.scala
Labels: dependency-change, p:pravega
