Repository akka/alpakka, pull requests merged in 2022-03, with the labels that each got.

#2806 AWS connectors: use AWS SDK 2.17.113
  dynamodb/src/test/java/docs/javadsl/RetryTest.java
  dynamodb/src/test/scala/docs/scaladsl/RetrySpec.scala
  project/Dependencies.scala
Labels: p:aws-s3, p:aws-sqs, p:aws-sns, p:dynamodb, p:aws-lambda, dependency-change, p:aws-event-bridge, p:awslambda

#2820 Use akka-http 10.2.9
  build.sbt
  docker-compose.yml
  dynamodb/src/test/java/docs/javadsl/ExampleTest.java
  dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ItemSpec.scala
  dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TableSpec.scala
  dynamodb/src/test/scala/docs/scaladsl/ExampleSpec.scala
  elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchConnectionSettings.scala
  elasticsearch/src/test/java/docs/javadsl/ElasticsearchTestBase.java
  elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchConnectorBehaviour.scala
  elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV5Spec.scala
  elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV7Spec.scala
  google-cloud-bigquery-storage/src/test/scala/akka/stream/alpakka/googlecloud/bigquery/storage/mock/BigQueryMockServer.scala
  google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
  google-cloud-pub-sub/src/test/scala/docs/scaladsl/IntegrationSpec.scala
  google-common/src/main/scala/akka/stream/alpakka/google/http/ForwardProxyHttpsContext.scala
  huawei-push-kit/src/main/scala/akka/stream/alpakka/huawei/pushkit/ForwardProxyHttpsContext.scala
  project/Dependencies.scala
  s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequest.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
  s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequestSpec.scala
  scripts/link-validator.conf
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
  sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceMockSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
  sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
  sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
  sse/src/test/scala/docs/scaladsl/EventSourceSpec.scala
Labels: p:aws-s3, p:aws-sqs, p:dynamodb, p:sse, p:google-cloud-pub-sub, p:elasticsearch, dependency-change, p:sqs, p:google-common, p:google-cloud-bigquery-storage, p:huawei-push-kit

#2824 Kinesis: remove cleanup function, separate batching and writing
  docs/src/main/paradox/kinesis.md
  kinesis/src/main/scala/akka/stream/alpakka/kinesis/javadsl/KinesisFlow.scala
  kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
  kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisFlowSpec.scala
  kinesis/src/test/scala/docs/scaladsl/KinesisSnippets.scala
Labels: p:kinesis, documentation

#2834 #1732: Moved Splitter and Aggregator to Akka Streams Cookbook …
  doc-examples/src/test/java/akka/stream/alpakka/eip/javadsl/SplitterExamples.java
  doc-examples/src/test/scala/akka/stream/alpakka/eip/scaladsl/SplitterExamples.scala
  docs/src/main/paradox/patterns.md
Labels: documentation

#2838 updated kinesis client to 2.4.0
  project/Dependencies.scala
Labels: p:kinesis, dependency-change

#2840 bump: Akka 2.6.19
  project/Dependencies.scala
Labels: dependency-change

#2842 AWS S3: Use testcontainer-scala-scalatest to setup Minio docker
  .github/workflows/check-build-test.yml
  docker-compose.yml
  docs/src/main/paradox/s3.md
  project/Dependencies.scala
  s3/src/test/scala/akka/stream/alpakka/s3/MinioContainer.scala
  s3/src/test/scala/akka/stream/alpakka/s3/MinioS3Test.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Labels: p:aws-s3, dependency-change, documentation

#2844 AWS S3: Include custom headers in all multipart copy requests
  docs/src/main/paradox/avroparquet.md
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
Labels: p:aws-s3, documentation

#2837 More recent versions of test and support libraries
  project/Dependencies.scala
  s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
Labels: p:aws-s3, dependency-change
