Repository akka/alpakka, pull requests merged in 2023-02, with the labels that each got.

#2951 bump(google-common): jwt-spray-json 9.0.2 (was 7.1.4)
  project/Dependencies.scala
Labels: dependency-change, p:google-common

#2954 bump: Google cloud SDK/emulator 416; Pub/Sub gRPC 1.123.1
  docker-compose.yml
  project/Dependencies.scala
Labels: p:google-cloud-pub-sub, p:google-cloud-pub-sub-grpc, dependency-change

#2956 Ensure to only pass sse headers to completeMultipartUpload
  s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
  s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
Labels: p:aws-s3

#2957 Scala3 builds
  .github/workflows/check-build-test.yml
  build.sbt
  cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSession.scala
  cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSessionPerformanceSpec.scala
  cassandra/src/test/scala/docs/javadsl/CassandraSessionSpec.scala
  csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
  csv/src/test/scala/docs/scaladsl/CsvSpec.scala
  mongodb/src/test/scala/docs/scaladsl/MongoSinkSpec.scala
  project/Common.scala
  project/Dependencies.scala
  project/Scala3.scala
Labels: p:cassandra, p:csv, p:mongodb, dependency-change
