Repository akka/alpakka, pull requests merged in 2023-04, with the labels that each got.

#2964 bump: Alpakka Kafka 4.0.2
  project/Dependencies.scala
Labels: dependency-change

#2966 Remove external mapr.com connector
  docs/src/main/paradox/external/mapr.md
  docs/src/main/paradox/index.md
Labels: documentation

#2962 chore: run link checking on JDK 11
  .github/workflows/link-validator.yml
Labels: documentation

#2970 fix: logger with proper class ref
  cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSessionPerformanceSpec.scala
  cassandra/src/test/scala/docs/javadsl/CassandraSessionSpec.scala
Labels: p:cassandra

#2969 fix(mqtt-streaming): Separate MQTT QoS by message type (#2969
  mqtt-streaming/src/main/mima-filters/5.1.0-M1.backwards.excludes/mqtt-streaming
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
  mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
  mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttCodecSpec.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
  mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Labels: api-change, p:mqtt-streaming
