Repository akka/alpakka, pull requests merged in 2024-09, with the labels that each got.

#3220 bump (Hbase, Hadoop): Hadoop 3.4, Hbase 2.6) fixes CVE-2021-37137
  hbase/src/main/scala/akka/stream/alpakka/hbase/impl/HBaseCapabilities.scala
  hbase/src/test/java/docs/javadsl/HBaseStageTest.java
  hbase/src/test/scala/docs/scaladsl/HBaseStageSpec.scala
  project/Dependencies.scala
Labels: p:hbase, p:hdfs, dependency-change

#3230 bump: scalatest 3.2.19 (was 3.2.18)
  project/Dependencies.scala
Labels: dependency-change

#3271 fix(couchbase): cli args in the same line
  couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseFlow.scala
  docker-compose.yml
Labels: p:couchbase

#3265 bump: mongo-scala-driver 4.11.4 (was 4.10.2)
  project/Dependencies.scala
Labels: p:mongodb, dependency-change

#3272 build(ironmq): disable tests to avoid docker pull error
  .github/workflows/check-build-test.yml
  docker-compose.yml
Labels: p:ironmq

#3231 bump: specs2-core 4.20.8 (was 4.20.5)
  project/Dependencies.scala
Labels: p:avroparquet, dependency-change

#3176 bump: com.ibm.mq.allclient 9.3.5.1 (was 9.3.5.0)
  project/Dependencies.scala
Labels: p:jms, dependency-change

#3264 bump: mockito-core 5.13.0 (was 4.11.0)
  project/Dependencies.scala
Labels: dependency-change

#3258 bump: sshj 0.39.0 (was 0.35.0)
  project/Dependencies.scala
Labels: p:ftp, dependency-change

#3262 bump: parquet-avro 1.14.2 (was 1.13.1)
  project/Dependencies.scala
Labels: p:avroparquet, dependency-change

#3266 bump: spring-context, spring-core 5.3.39 (was 5.3.33)
  project/Dependencies.scala
Labels: p:spring-web, dependency-change

#3177 bump: amqp-client 5.21.0 (was 5.20.0)
  project/Dependencies.scala
Labels: p:amqp, dependency-change

#3218 bump: cats-core 2.12.0 (was 2.10.0)
  project/Dependencies.scala
Labels: p:hdfs, dependency-change

#3256 bump: google-auth-library-credentials, ... 1.24.1 (was 1.24.0)
  project/Dependencies.scala
Labels: dependency-change, p:google-common

#3248 bump: h2 2.3.232 (was 2.1.214)
  project/Dependencies.scala
Labels: p:slick, dependency-change

#3173 bump: proto-google-cloud-bigquerystorage-v1 1.23.2 (was 1.22.8)
  project/Dependencies.scala
Labels: dependency-change, p:google-cloud-bigquery-storage

#3206 bump: shapeless 2.3.12 (was 2.3.10)
  project/Dependencies.scala
Labels: p:geode, dependency-change

#3192 bump: scalacheck 1.17.1 (was 1.17.0)
  project/Dependencies.scala
Labels: p:avroparquet, dependency-change

#3080 bump: pravega-client 0.13.0 (was 0.10.2)
  project/Dependencies.scala
Labels: dependency-change, p:pravega

#3244 bump: avro 1.12.0 (was 1.11.3)
  project/Dependencies.scala
Labels: p:avroparquet, dependency-change, p:google-cloud-bigquery-storage
