Repository akka/alpakka, pull requests merged in 2024-02, with the labels that each got.

#3082 bump(tests): activemq-broker, activemq-client 5.16.7 (was 5.16.4)
  project/Dependencies.scala
Labels: dependency-change

#3097 bump(avro parquet tests): scalacheck 1.17.0 (was 1.15.4)
  project/Dependencies.scala
Labels: p:avroparquet, dependency-change

#3120 bump(s3 tests): wiremock-jre8 2.35.2 (was 2.32.0)
  project/Dependencies.scala
Labels: dependency-change

#3116 bump: solr-solrj, solr-test-framework 8.11.3 (was 8.11.1)
  project/Dependencies.scala
Labels: p:solr, dependency-change

#3098 bump: sbt-scalafmt 2.5.2 (was 2.5.0)
  project/plugins.sbt
Labels: alpakka-itself

#3113 bump: jnr-unixsocket 0.38.22 (was 0.38.5)
  project/Dependencies.scala
Labels: p:unix-domain-socket, dependency-change

#3132 Handle session thread
  jms/src/main/scala/akka/stream/alpakka/jms/impl/Sessions.scala
Labels: p:jms
