Repository akka/alpakka, pull requests merged in 2024-04, with the labels that each got.

#3087 bump: hadoop-client, hadoop-common, ... 3.3.6 (was 3.3.3)
  project/Dependencies.scala
Labels: p:hbase, p:hdfs, dependency-change

#3054 bump: aalto-xml 1.3.2 (was 1.2.2)
  project/Dependencies.scala
Labels: p:xml, dependency-change

#3060 bump: jwt-json-common 9.4.6 (was 9.4.4)
  .scala-steward.conf
  project/Dependencies.scala
Labels: dependency-change

#3104 bump: spring-boot-autoconfigure, ... 2.7.18 (was 2.5.15)
  project/Dependencies.scala
Labels: p:spring-web, dependency-change

#3065 bump(pub/sub grpc): google-cloud-pubsub protobuf 1.123.20 (was 1.123.1)
  project/Dependencies.scala
Labels: p:google-cloud-pub-sub-grpc, dependency-change

#3063 bump(bigquery storage gRPC): proto-google-cloud-bigquerystorage-v1 protobuf 1.22.8 (was 1.22.0)
  project/Dependencies.scala
Labels: dependency-change, p:google-cloud-bigquery-storage

#3163 revert: logback may not pull slf4j 2.x
  project/Dependencies.scala
  solr/src/test/scala/docs/scaladsl/SolrSpec.scala
Labels: p:solr, dependency-change

#3071 bump: azure-storage 8.6.6 (was 8.0.0)
  project/Dependencies.scala
Labels: p:azure-storage-queue, dependency-change

#3052 bump: shapeless 2.3.10 (was 2.3.3)
  project/Dependencies.scala
Labels: p:geode, dependency-change

#3164 bump(sqs test): ElasticMQ image 1.5.8 (was 1.3.4)
  docker-compose.yml
Labels: p:aws-sqs

#3069 bump: sshj 0.35.0 (was 0.33.0)
  project/Dependencies.scala
Labels: p:ftp, dependency-change

#3074 bump(avroparquet test): avro4s-core 4.1.2 (was 3.0.9)
  project/Dependencies.scala
Labels: p:avroparquet, dependency-change

#3078 bump: akka-http-circe 1.39.2 (was 1.29.1)
  project/Dependencies.scala
Labels: p:ironmq, dependency-change

#3167 JMS: Swallow IBM MQ exception
  jms/src/main/scala/akka/stream/alpakka/jms/impl/Sessions.scala
Labels: p:jms

#3166 bump: hadoop-hdfs, ... 3.3.6 (was 3.3.3)
  project/Dependencies.scala
Labels: p:hbase, p:hdfs, dependency-change

#3168 Remove wrong version badges
  README.md
  docs/src/main/paradox/other-docs/webinars-presentations-articles.md
Labels: documentation

#3170 chore: New license for tests and docs
  LICENSE
  README.md
  amqp/src/test/LICENSE
  avroparquet-tests/src/test/LICENSE
  aws-event-bridge/src/test/LICENSE
  awslambda/src/test/LICENSE
  azure-storage-queue/src/test/LICENSE
  cassandra/src/test/LICENSE
  couchbase/src/test/LICENSE
  csv/src/test/LICENSE
  doc-examples/src/test/LICENSE
  docs/LICENSE
  dynamodb/src/test/LICENSE
  elasticsearch/src/test/LICENSE
  file/src/test/LICENSE
  ftp/src/test/LICENSE
  geode/src/test/LICENSE
  google-cloud-bigquery-storage/src/test/LICENSE
  google-cloud-bigquery/src/test/LICENSE
  google-cloud-pub-sub-grpc/src/test/LICENSE
  google-cloud-pub-sub/src/test/LICENSE
  google-cloud-storage/src/test/LICENSE
  google-common/src/test/LICENSE
  google-fcm/src/test/LICENSE
  hbase/src/test/LICENSE
  hdfs/src/test/LICENSE
  huawei-push-kit/src/test/LICENSE
  influxdb/src/test/LICENSE
  ironmq/src/test/LICENSE
  jakarta-jms/src/test/LICENSE
  jms/src/test/LICENSE
  json-streaming/src/test/LICENSE
  kinesis/src/test/LICENSE
  kudu/src/test/LICENSE
  mongodb/src/test/LICENSE
  mqtt-streaming/src/test/LICENSE
  mqtt/src/test/LICENSE
  pravega/src/test/LICENSE
  reference/src/test/LICENSE
  s3/src/test/LICENSE
  simple-codecs/src/test/LICENSE
  slick/src/test/LICENSE
  sns/src/test/LICENSE
  solr/src/test/LICENSE
  spring-web/src/test/LICENSE
  sqs/src/test/LICENSE
  sse/src/test/LICENSE
  text/src/test/LICENSE
  udp/src/test/LICENSE
  unix-domain-socket/src/test/LICENSE
  xml/src/test/LICENSE
Labels: p:ftp, p:amqp, p:hbase, p:geode, p:dynamodb, p:google-cloud-pub-sub, p:elasticsearch, p:cassandra, p:csv, p:file, p:aws-lambda, p:azure-storage-queue, p:google-fcm, p:ironmq, p:hdfs, p:google-cloud-pub-sub-grpc, p:couchbase, documentation, p:google-cloud-storage, p:influxdb, p:aws-event-bridge, p:google-cloud-bigquery, p:google-common, p:google-cloud-bigquery-storage, p:huawei-push-kit, p:jakarta-jms
