Repository akka/alpakka, pull requests merged in 2024-03, with the labels that each got.

#3142 chore: bump GH actions; replace release drafter
  .github/release-drafter.yml
  .github/release.yml
  .github/workflows/check-build-test.yml
  .github/workflows/fossa.yml
  .github/workflows/link-validator.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  CODE_OF_CONDUCT.md
  README.md
  docs/release-train-issue-template.md
  project/plugins.sbt
Labels: documentation

#3161 Make Scala Steward less eager
  .scala-steward.conf
  project/Dependencies.scala
Labels: dependency-change

#3162 Drop OrientDB
  .github/autolabeler.yml
  .github/release.yml
  .github/workflows/check-build-test.yml
  build.sbt
  docker-compose.yml
  docs/src/main/paradox/index.md
  docs/src/main/paradox/orientdb.md
  orientdb/src/main/resources/reference.conf
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/OrientDbSourceSettings.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/OrientDbWriteSettings.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/impl/OrientDbFlowStage.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/impl/OrientDbSourceStage.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDbFlow.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDbSink.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDbSource.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/model.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDbFlow.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDbSink.scala
  orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDbSource.scala
  orientdb/src/test/java/docs/javadsl/OrientDbTest.java
  orientdb/src/test/resources/application.conf
  orientdb/src/test/resources/logback-test.xml
  orientdb/src/test/scala/docs/scaladsl/OrientDbSpec.scala
  project/project-info.conf
Labels: p:orientdb, documentation

#3094 bump(test): mockito-core, mockito-inline 4.11.0 (was 4.8.1)
  project/Dependencies.scala
Labels: dependency-change

#3102 bump(AvroParquet tests): specs2-core 4.20.5 (was 4.8.3)
  project/Dependencies.scala
Labels: dependency-change

#3086 bump: geode-core, geode-cq 1.15.1 (was 1.15.0)
  docker-compose.yml
  project/Dependencies.scala
Labels: dependency-change

#3095 bump: mongo-scala-driver 4.10.2 (was 4.10.0)
  project/Dependencies.scala
Labels: p:mongodb, dependency-change

#3112 bump: jffi 1.3.13 (was 1.3.1)
  project/Dependencies.scala
Labels: p:unix-domain-socket, dependency-change

#3114 bump: google-auth-library-credentials, ... 1.23.0 (was 1.15.0)
  project/Dependencies.scala
Labels: p:google-cloud-pub-sub, p:google-fcm, p:google-cloud-pub-sub-grpc, dependency-change, p:google-cloud-storage, p:google-cloud-bigquery, p:google-common, p:google-cloud-bigquery-storage

#3133 bump(test): com.ibm.mq.allclient 9.3.5.0 (was 9.2.5.0)
  project/Dependencies.scala
Labels: p:jms, dependency-change

#3135 bump: scala3-library 3.3.3 (was 3.3.1)
  project/Dependencies.scala
Labels: dependency-change

#3146 build: Verify compilation JDK 21
  .github/workflows/check-build-test.yml
  build.sbt
  cassandra/src/test/java/docs/javadsl/CassandraTestHelper.java
  docker-compose.yml
  docs/src/main/paradox/google-cloud-bigquery-storage.md
  docs/src/main/paradox/google-cloud-pub-sub-grpc.md
  project/Dependencies.scala
Labels: p:cassandra, dependency-change, documentation

#3076 bump(test): play-json 2.9.4 (was 2.9.2)
  project/Dependencies.scala
Labels: p:couchbase, dependency-change

#3053 bump: couchbase java-client 2.7.23 (was 2.7.16)
  project/Dependencies.scala
Labels: p:couchbase, dependency-change

#3125 bump(test): wiremock-jre8 3.0.1 (was 2.35.2)
  project/Dependencies.scala
Labels: p:aws-s3, dependency-change

#3068 bump(slick test): h2 2.1.214 (was 2.1.210)
  project/Dependencies.scala
Labels: p:slick, dependency-change

#3061 bump(Google PubSub test): wiremock 3.0.1 (was 2.27.2)
  project/Dependencies.scala
Labels: p:google-cloud-pub-sub, dependency-change

#3051 bump: logback-classic 1.4.14 (was 1.4.12)
  project/Dependencies.scala
Labels: dependency-change

#3160 bump: auth, dynamodb, eventbridge, firehose, ... 2.25.16 (was 2.17.295)
  project/Dependencies.scala
Labels: p:aws-sqs, p:aws-sns, p:kinesis, p:dynamodb, p:aws-lambda, dependency-change, p:aws-event-bridge

#3149 bump: spring-context, spring-core 5.3.33 (was 5.2.25.RELEASE)
  project/Dependencies.scala
Labels: p:spring-web, dependency-change

#3139 bump: slick, slick-hikaricp 3.5.0 (was 3.4.1)
  build.sbt
  project/Dependencies.scala
  slick/src/main/mima-filters/8.0.x.backwards.excludes
Labels: p:slick, dependency-change

#3159 bump(jakarta-jms test): artemis-jakarta-client, ... 2.33.0 (was 2.31.2)
  jakarta-jms/src/test/java/docs/javadsl/JmsConnectorsTest.java
  jakarta-jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
  project/Dependencies.scala
Labels: dependency-change, p:jakarta-jms

#3073 bump: amqp-client 5.20.0 (was 5.18.0)
  project/Dependencies.scala
Labels: p:amqp, dependency-change

#3088 bump: hbase-common, hbase-shaded-client 1.4.14 (was 1.4.13)
  project/Dependencies.scala
Labels: p:hbase, dependency-change

#3066 bump(test): jimfs 1.3.0 (was 1.2)
  project/Dependencies.scala
Labels: dependency-change
