Repository akka/alpakka, pull requests merged in 2024-12, with the labels that each got.

#3322 bump: Akka gRPC 2.5.0 (was M1)
  project/plugins.sbt
Labels: p:google-cloud-pub-sub-grpc

#3285 bump: google-cloud-pubsub 1.132.4 (was 1.132.2)
  project/Dependencies.scala
Labels: p:google-cloud-pub-sub-grpc

#3281 bump: jnr-unixsocket 0.38.23 (was 0.38.22)
  project/Dependencies.scala
Labels: p:unix-domain-socket

#3288 bump: sslcontext-kickstart-for-pem 8.3.7 (was 8.3.5)
  project/Dependencies.scala
Labels: p:ftp

#3294 bump: scala-library 2.13.15 (was 2.13.12)
  google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
  jakarta-jms/src/test/scala/akka/stream/alpakka/jakartajms/impl/JmsMessageProducerSpec.scala
  jakarta-jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
  jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
  jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
  project/Common.scala
  project/Dependencies.scala
Labels: p:jms, dependency-change, p:google-cloud-storage, p:jakarta-jms
