Repository akka/alpakka, pull requests merged in 2024-08, with the labels that each got.

#3251 Docker compose (without hyphen)
  .github/workflows/check-build-test.yml
  build.sbt
  docker-compose.yml
  docs/src/main/paradox/aws-event-bridge.md
  docs/src/main/paradox/ftp.md
  docs/src/main/paradox/google-cloud-pub-sub-grpc.md
  docs/src/main/paradox/mqtt.md
  scripts/ftp-servers.sh
  scripts/link-validator.conf
Labels: documentation

#3252 AWS SQS: copy delay seconds on batch request
  sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
Labels: p:aws-sqs, p:sqs

#3207 bump: aalto-xml 1.3.3 (was 1.3.2)
  project/Dependencies.scala
Labels: p:xml, dependency-change

#3223 bump: google-auth-library-credentials, ... 1.24.0 (was 1.23.0)
  project/Dependencies.scala
Labels: dependency-change, p:google-common

#3179 bump: slick, slick-hikaricp 3.5.1 (was 3.5.0)
  project/Dependencies.scala
Labels: p:slick, dependency-change
