Repository akka/alpakka, pull requests merged in 2025-10, with the labels that each got.

#3429 FTP (test): Bump and rename sslcontext-kicktart to ayza
  project/Dependencies.scala
Labels: dependency-change

#3421 bump (Geode Test): log4j-to-slf4j 2.25.2 (was 2.17.2)
  project/Dependencies.scala
Labels: p:geode, dependency-change

#3419 bump: google-cloud-pubsub 1.141.5 (was 1.132.4)
  project/Dependencies.scala
Labels: p:google-cloud-pub-sub, dependency-change

#3415 bump: jackson-core 2.18.4 (was 2.18.3)
  project/Dependencies.scala
Labels: dependency-change

#3403 bump: sshj 0.40.0 (was 0.39.0)
  project/Dependencies.scala
Labels: dependency-change

#3375 bump: hbase-common, hbase-shaded-client 2.6.2 (was 2.6.1)
  project/Dependencies.scala
Labels: p:hbase, dependency-change
